version: '3'

services:
  mcp-db:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/mcp-servers.db

  # SQLite Web UI
  mcp-db-browser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    platform: linux/arm64
    ports:
      - "3001:3000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data

volumes:
  data:
    driver: local
